//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reconfig.Domain.Handlers.Gum {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://iadb.org/", ConfigurationName="Gum.GUMSoap")]
    public interface GUMSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListRealms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListRealms(string langCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListRealmsByGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListRealmsByGroup(string langCode, string gumGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ValidateAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonAuth ValidateAD(string domain, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListGroupsInRealms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListGroupsInRealms(string realmName, string groupTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListGroupsInGroupRecursive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.GUMGroup[] ListGroupsInGroupRecursive(int groupID, string groupName, string realmName, int recursionDepth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/GetPersonInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonDetails GetPersonInfo(int personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/GetBankEmployeeInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.BankEmployeeDetails GetBankEmployeeInfo(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/GetBankEmployeeList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.BankEmployeeDetails[] GetBankEmployeeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/IsUserInGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsUserInGroup(int personID, string gumGroupName, bool includeDelegators);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/IsUserInGroupRealm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsUserInGroupRealm(int personID, string gumGroupName, string realmName, bool includeDelegators);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/GetGroupInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.GUMGroup GetGroupInfo(string gumGroupName, string realmName, bool allRealms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ValidateExternal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonAuth ValidateExternal(string oneTimeToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListDelegates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonDetails[] ListDelegates(int personID, string realmName, bool allRealms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListDelegators", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonDetails[] ListDelegators(int personID, string realmName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListPersonContacts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonDetails[] ListPersonContacts(int personID, string gumGroupName, string realmName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListApplications", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListApplications(string realmName, bool includeGlobal, string langCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListPersonRealms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListPersonRealms(int personID, bool includeDelegators);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListPersonGroupsIncludingGlobal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.GUMGroup[] ListPersonGroupsIncludingGlobal(int personID, string realmName, bool includeDelegators, bool showGroupData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListPersonGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.GUMGroup[] ListPersonGroups(int personID, string realmName, bool includeDelegators, bool includeGlobalGroups, bool showGroupData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/CreatePerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonDetails CreatePerson(
                    string lastName, 
                    string firstName, 
                    string alias, 
                    int applicationID, 
                    System.DateTime dateOfBirth, 
                    string genderCD, 
                    string streetAddress, 
                    int cityID, 
                    string postalCode, 
                    string email, 
                    string phoneNumber, 
                    int formOfAddressID, 
                    string preferredLanguage, 
                    string comments, 
                    string nationalityCD, 
                    int createdByPersonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/UpdatePerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonDetails UpdatePerson(int personID, System.DateTime dateOfBirth, string genderCD, string streetAddress, int cityID, string postalCode, string email, string phoneNumber, int formOfAddressID, string preferredLanguage, string comments, int updatedByPersonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/CreatePersonAlias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreatePersonAlias(int personID, string lastName, string firstName, string alias, int applicationID, bool setAsPreferredAlias, int createdByPersonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/CreatePersonGroupMembership", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonGroupMembership CreatePersonGroupMembership(int personID, int gumGroupID, System.DateTime positionFromDate, System.DateTime positionToDate, string positionEmail, string positionPhone, string positionCountryCD, int positionRanking1, int positionRanking2, int positionTitleID, string positionTitleText, string positionOffice, bool positionPointOfContact, int createdByPersonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/UpdatePersonGroupMembership", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdatePersonGroupMembership(
                    int personGroupMembershipID, 
                    System.DateTime positionFromDate, 
                    System.DateTime positionToDate, 
                    string positionEmail, 
                    string positionPhone, 
                    string positionCountryCD, 
                    int positionRanking1, 
                    int positionRanking2, 
                    string positionOffice, 
                    string positionVIP, 
                    string positionTempVIP, 
                    bool positionPointOfContact, 
                    string positionInstContactType, 
                    string positionSkype, 
                    string positionTwitter, 
                    string positionComments, 
                    int titleID, 
                    string titleGender, 
                    string titleType, 
                    string titleShortEN, 
                    string titleShortES, 
                    string titleShortPT, 
                    string titleShortFR, 
                    string titleLongEN, 
                    string titleLongES, 
                    string titleLongPT, 
                    string titleLongFR, 
                    int updatedByPersonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/GetPersonGroupMembershipInfoByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonGroupMembership GetPersonGroupMembershipInfoByID(int personGroupMembershipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/GetPersonGroupMembershipInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonGroupMembership GetPersonGroupMembershipInfo(int personID, int gumGroupId, System.DateTime fromDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/UpdatePersonGroupMembershipExpirationDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonGroupMembership UpdatePersonGroupMembershipExpirationDate(int personGroupMembershipID, System.DateTime expirationDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/AddPersonImageFromFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddPersonImageFromFile(int personID, string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/AddPersonImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddPersonImage(int personID, string pictureStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/GetPersonImageFullSize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPersonImageFullSize(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/GetPersonImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPersonImage(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/GenerateOneTimePasscode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GenerateOneTimePasscode(int personID, System.DateTime OTPExpirationDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListMembers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonDetails[] ListMembers(string realmName, bool allRealms, string gumGroupName, bool includeDelegates, bool showGroupData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListMemberships", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonDetails[] ListMemberships(string realmName, bool allRealms, string gumGroupName, bool includeDelegates, bool showGroupData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/ListEmailsByGroupNoRecursive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonDetails[] ListEmailsByGroupNoRecursive(string realmName, string gumGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/UpdatePersonGroupMembershipRanking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.PersonGroupMembership UpdatePersonGroupMembershipRanking(int personGroupMembershipID, int ranking1, int ranking2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/GetCityInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.CityDetails GetCityInfo(string cityID, string langCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/_GetGroupRecursion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string _GetGroupRecursion(int gumGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/_GetGroupRecursionUp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string _GetGroupRecursionUp(int gumGroupId);
        
        // CODEGEN: Generating message contract since the wrapper name (USE_ListPersonGroupsIncludingGlobal_INSTEAD) of message USE_ListPersonGroupsIncludingGlobal_INSTEAD does not match the default value (ADListPersonGroupsIncludingGlobal)
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/USE_ListPersonGroupsIncludingGlobal_INSTEAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.USE_ListPersonGroupsIncludingGlobal_INSTEAD1 ADListPersonGroupsIncludingGlobal(Reconfig.Domain.Handlers.Gum.USE_ListPersonGroupsIncludingGlobal_INSTEAD request);
        
        // CODEGEN: Generating message contract since the wrapper name (USE_ListPersonGroups_INSTEAD) of message USE_ListPersonGroups_INSTEAD does not match the default value (ADListPersonGroups)
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/USE_ListPersonGroups_INSTEAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.USE_ListPersonGroups_INSTEAD1 ADListPersonGroups(Reconfig.Domain.Handlers.Gum.USE_ListPersonGroups_INSTEAD request);
        
        // CODEGEN: Generating message contract since the wrapper name (USE_ListMembers_INSTEAD) of message USE_ListMembers_INSTEAD does not match the default value (ADListMembers)
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/USE_ListMembers_INSTEAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.USE_ListMembers_INSTEAD1 ADListMembers(Reconfig.Domain.Handlers.Gum.USE_ListMembers_INSTEAD request);
        
        // CODEGEN: Generating message contract since the wrapper name (USE_IsUserInGroup_INSTEAD) of message USE_IsUserInGroup_INSTEAD does not match the default value (ADIsUserInGroup)
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/USE_IsUserInGroup_INSTEAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.USE_IsUserInGroup_INSTEAD1 ADIsUserInGroup(Reconfig.Domain.Handlers.Gum.USE_IsUserInGroup_INSTEAD request);
        
        // CODEGEN: Generating message contract since the wrapper name (USE_IsUserInGroupRealm_INSTEAD) of message USE_IsUserInGroupRealm_INSTEAD does not match the default value (ADIsUserInGroupRealm)
        [System.ServiceModel.OperationContractAttribute(Action="http://iadb.org/USE_IsUserInGroupRealm_INSTEAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reconfig.Domain.Handlers.Gum.USE_IsUserInGroupRealm_INSTEAD1 ADIsUserInGroupRealm(Reconfig.Domain.Handlers.Gum.USE_IsUserInGroupRealm_INSTEAD request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iadb.org/")]
    public partial class PersonAuth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int personIDField;
        
        private string authenticationTypeField;
        
        private string domainField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PersonID {
            get {
                return this.personIDField;
            }
            set {
                this.personIDField = value;
                this.RaisePropertyChanged("PersonID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AuthenticationType {
            get {
                return this.authenticationTypeField;
            }
            set {
                this.authenticationTypeField = value;
                this.RaisePropertyChanged("AuthenticationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("Domain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iadb.org/")]
    public partial class CityDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryCodeField;
        
        private string countryNameField;
        
        private string countrySubdivisionCodeField;
        
        private string countrySubdivisionNameField;
        
        private bool countrySubdivisionActiveField;
        
        private int cityIdField;
        
        private string cityNameField;
        
        private bool cityActiveField;
        
        private string cityPopulationField;
        
        private string cityGMTOffsetField;
        
        private string cityDSTOffsetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
                this.RaisePropertyChanged("CountryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CountrySubdivisionCode {
            get {
                return this.countrySubdivisionCodeField;
            }
            set {
                this.countrySubdivisionCodeField = value;
                this.RaisePropertyChanged("CountrySubdivisionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CountrySubdivisionName {
            get {
                return this.countrySubdivisionNameField;
            }
            set {
                this.countrySubdivisionNameField = value;
                this.RaisePropertyChanged("CountrySubdivisionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool CountrySubdivisionActive {
            get {
                return this.countrySubdivisionActiveField;
            }
            set {
                this.countrySubdivisionActiveField = value;
                this.RaisePropertyChanged("CountrySubdivisionActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CityId {
            get {
                return this.cityIdField;
            }
            set {
                this.cityIdField = value;
                this.RaisePropertyChanged("CityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
                this.RaisePropertyChanged("CityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool CityActive {
            get {
                return this.cityActiveField;
            }
            set {
                this.cityActiveField = value;
                this.RaisePropertyChanged("CityActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CityPopulation {
            get {
                return this.cityPopulationField;
            }
            set {
                this.cityPopulationField = value;
                this.RaisePropertyChanged("CityPopulation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CityGMTOffset {
            get {
                return this.cityGMTOffsetField;
            }
            set {
                this.cityGMTOffsetField = value;
                this.RaisePropertyChanged("CityGMTOffset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CityDSTOffset {
            get {
                return this.cityDSTOffsetField;
            }
            set {
                this.cityDSTOffsetField = value;
                this.RaisePropertyChanged("CityDSTOffset");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iadb.org/")]
    public partial class PersonGroupMembership : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int personGroupMembershipIDField;
        
        private int fK_GumGroupIDField;
        
        private int fK_MemberPersonIDField;
        
        private System.DateTime fromDateField;
        
        private System.DateTime toDateField;
        
        private string emailField;
        
        private string phoneNumberField;
        
        private string fK_CountryCodeOfAssignmentField;
        
        private string ranking1Field;
        
        private string ranking2Field;
        
        private string fK_PositionTitleIDField;
        
        private string officeField;
        
        private bool vIPField;
        
        private bool tempVIPField;
        
        private bool institutionalContactField;
        
        private string positionTitleENField;
        
        private string positionTitleESField;
        
        private string positionTitlePTField;
        
        private string positionTitleFRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PersonGroupMembershipID {
            get {
                return this.personGroupMembershipIDField;
            }
            set {
                this.personGroupMembershipIDField = value;
                this.RaisePropertyChanged("PersonGroupMembershipID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int FK_GumGroupID {
            get {
                return this.fK_GumGroupIDField;
            }
            set {
                this.fK_GumGroupIDField = value;
                this.RaisePropertyChanged("FK_GumGroupID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int FK_MemberPersonID {
            get {
                return this.fK_MemberPersonIDField;
            }
            set {
                this.fK_MemberPersonIDField = value;
                this.RaisePropertyChanged("FK_MemberPersonID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("FromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime ToDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
                this.RaisePropertyChanged("ToDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FK_CountryCodeOfAssignment {
            get {
                return this.fK_CountryCodeOfAssignmentField;
            }
            set {
                this.fK_CountryCodeOfAssignmentField = value;
                this.RaisePropertyChanged("FK_CountryCodeOfAssignment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Ranking1 {
            get {
                return this.ranking1Field;
            }
            set {
                this.ranking1Field = value;
                this.RaisePropertyChanged("Ranking1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Ranking2 {
            get {
                return this.ranking2Field;
            }
            set {
                this.ranking2Field = value;
                this.RaisePropertyChanged("Ranking2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FK_PositionTitleID {
            get {
                return this.fK_PositionTitleIDField;
            }
            set {
                this.fK_PositionTitleIDField = value;
                this.RaisePropertyChanged("FK_PositionTitleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Office {
            get {
                return this.officeField;
            }
            set {
                this.officeField = value;
                this.RaisePropertyChanged("Office");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool VIP {
            get {
                return this.vIPField;
            }
            set {
                this.vIPField = value;
                this.RaisePropertyChanged("VIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool TempVIP {
            get {
                return this.tempVIPField;
            }
            set {
                this.tempVIPField = value;
                this.RaisePropertyChanged("TempVIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool InstitutionalContact {
            get {
                return this.institutionalContactField;
            }
            set {
                this.institutionalContactField = value;
                this.RaisePropertyChanged("InstitutionalContact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PositionTitleEN {
            get {
                return this.positionTitleENField;
            }
            set {
                this.positionTitleENField = value;
                this.RaisePropertyChanged("PositionTitleEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PositionTitleES {
            get {
                return this.positionTitleESField;
            }
            set {
                this.positionTitleESField = value;
                this.RaisePropertyChanged("PositionTitleES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string PositionTitlePT {
            get {
                return this.positionTitlePTField;
            }
            set {
                this.positionTitlePTField = value;
                this.RaisePropertyChanged("PositionTitlePT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string PositionTitleFR {
            get {
                return this.positionTitleFRField;
            }
            set {
                this.positionTitleFRField = value;
                this.RaisePropertyChanged("PositionTitleFR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iadb.org/")]
    public partial class BankEmployeeDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int personIDField;
        
        private int pGMIDField;
        
        private string domainField;
        
        private string userNameField;
        
        private string aliasField;
        
        private string emailField;
        
        private string phoneNumberField;
        
        private string officeField;
        
        private string countryCodeOfAssignmentField;
        
        private int positionTitleIDField;
        
        private string positionTitleENField;
        
        private string positionTitleESField;
        
        private string positionTitlePTField;
        
        private string positionTitleFRField;
        
        private string employeeNumberField;
        
        private string orgUnitCodeField;
        
        private string departmentCodeField;
        
        private string rollupOrgUnitCodeField;
        
        private string employeeTypeField;
        
        private string groupNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PersonID {
            get {
                return this.personIDField;
            }
            set {
                this.personIDField = value;
                this.RaisePropertyChanged("PersonID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PGMID {
            get {
                return this.pGMIDField;
            }
            set {
                this.pGMIDField = value;
                this.RaisePropertyChanged("PGMID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("Domain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("Alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Office {
            get {
                return this.officeField;
            }
            set {
                this.officeField = value;
                this.RaisePropertyChanged("Office");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CountryCodeOfAssignment {
            get {
                return this.countryCodeOfAssignmentField;
            }
            set {
                this.countryCodeOfAssignmentField = value;
                this.RaisePropertyChanged("CountryCodeOfAssignment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int PositionTitleID {
            get {
                return this.positionTitleIDField;
            }
            set {
                this.positionTitleIDField = value;
                this.RaisePropertyChanged("PositionTitleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PositionTitleEN {
            get {
                return this.positionTitleENField;
            }
            set {
                this.positionTitleENField = value;
                this.RaisePropertyChanged("PositionTitleEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PositionTitleES {
            get {
                return this.positionTitleESField;
            }
            set {
                this.positionTitleESField = value;
                this.RaisePropertyChanged("PositionTitleES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PositionTitlePT {
            get {
                return this.positionTitlePTField;
            }
            set {
                this.positionTitlePTField = value;
                this.RaisePropertyChanged("PositionTitlePT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PositionTitleFR {
            get {
                return this.positionTitleFRField;
            }
            set {
                this.positionTitleFRField = value;
                this.RaisePropertyChanged("PositionTitleFR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string EmployeeNumber {
            get {
                return this.employeeNumberField;
            }
            set {
                this.employeeNumberField = value;
                this.RaisePropertyChanged("EmployeeNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string OrgUnitCode {
            get {
                return this.orgUnitCodeField;
            }
            set {
                this.orgUnitCodeField = value;
                this.RaisePropertyChanged("OrgUnitCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DepartmentCode {
            get {
                return this.departmentCodeField;
            }
            set {
                this.departmentCodeField = value;
                this.RaisePropertyChanged("DepartmentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string RollupOrgUnitCode {
            get {
                return this.rollupOrgUnitCodeField;
            }
            set {
                this.rollupOrgUnitCodeField = value;
                this.RaisePropertyChanged("RollupOrgUnitCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string EmployeeType {
            get {
                return this.employeeTypeField;
            }
            set {
                this.employeeTypeField = value;
                this.RaisePropertyChanged("EmployeeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("GroupName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iadb.org/")]
    public partial class PersonDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PersonAuth personAuthField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string aliasField;
        
        private System.DateTime dateOfBirthField;
        
        private string genderField;
        
        private string streetAddressField;
        
        private string cityIDField;
        
        private string postalCodeField;
        
        private string emailField;
        
        private string phoneNumberField;
        
        private string formOfAddressIDField;
        
        private string preferredLanguageField;
        
        private string commentsField;
        
        private bool activeField;
        
        private string onBehalfOfField;
        
        private string groupLevelField;
        
        private string groupIDField;
        
        private string groupParentField;
        
        private int personGroupMembershipIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PersonAuth PersonAuth {
            get {
                return this.personAuthField;
            }
            set {
                this.personAuthField = value;
                this.RaisePropertyChanged("PersonAuth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("Alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("DateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StreetAddress {
            get {
                return this.streetAddressField;
            }
            set {
                this.streetAddressField = value;
                this.RaisePropertyChanged("StreetAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CityID {
            get {
                return this.cityIDField;
            }
            set {
                this.cityIDField = value;
                this.RaisePropertyChanged("CityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FormOfAddressID {
            get {
                return this.formOfAddressIDField;
            }
            set {
                this.formOfAddressIDField = value;
                this.RaisePropertyChanged("FormOfAddressID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PreferredLanguage {
            get {
                return this.preferredLanguageField;
            }
            set {
                this.preferredLanguageField = value;
                this.RaisePropertyChanged("PreferredLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string OnBehalfOf {
            get {
                return this.onBehalfOfField;
            }
            set {
                this.onBehalfOfField = value;
                this.RaisePropertyChanged("OnBehalfOf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string GroupLevel {
            get {
                return this.groupLevelField;
            }
            set {
                this.groupLevelField = value;
                this.RaisePropertyChanged("GroupLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
                this.RaisePropertyChanged("GroupID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string GroupParent {
            get {
                return this.groupParentField;
            }
            set {
                this.groupParentField = value;
                this.RaisePropertyChanged("GroupParent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int PersonGroupMembershipID {
            get {
                return this.personGroupMembershipIDField;
            }
            set {
                this.personGroupMembershipIDField = value;
                this.RaisePropertyChanged("PersonGroupMembershipID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iadb.org/")]
    public partial class GUMGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int gUMGroupIDField;
        
        private string groupNameField;
        
        private int realmIDField;
        
        private string realmNameField;
        
        private string groupTypeCodeField;
        
        private string domainField;
        
        private string aDGroupNameField;
        
        private string onBehalfOfField;
        
        private string groupLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int GUMGroupID {
            get {
                return this.gUMGroupIDField;
            }
            set {
                this.gUMGroupIDField = value;
                this.RaisePropertyChanged("GUMGroupID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("GroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RealmID {
            get {
                return this.realmIDField;
            }
            set {
                this.realmIDField = value;
                this.RaisePropertyChanged("RealmID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RealmName {
            get {
                return this.realmNameField;
            }
            set {
                this.realmNameField = value;
                this.RaisePropertyChanged("RealmName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string GroupTypeCode {
            get {
                return this.groupTypeCodeField;
            }
            set {
                this.groupTypeCodeField = value;
                this.RaisePropertyChanged("GroupTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("Domain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ADGroupName {
            get {
                return this.aDGroupNameField;
            }
            set {
                this.aDGroupNameField = value;
                this.RaisePropertyChanged("ADGroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OnBehalfOf {
            get {
                return this.onBehalfOfField;
            }
            set {
                this.onBehalfOfField = value;
                this.RaisePropertyChanged("OnBehalfOf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string GroupLevel {
            get {
                return this.groupLevelField;
            }
            set {
                this.groupLevelField = value;
                this.RaisePropertyChanged("GroupLevel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="USE_ListPersonGroupsIncludingGlobal_INSTEAD", WrapperNamespace="http://iadb.org/", IsWrapped=true)]
    public partial class USE_ListPersonGroupsIncludingGlobal_INSTEAD {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=0)]
        public int personID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=1)]
        public string realmName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=2)]
        public bool includeDelegators;
        
        public USE_ListPersonGroupsIncludingGlobal_INSTEAD() {
        }
        
        public USE_ListPersonGroupsIncludingGlobal_INSTEAD(int personID, string realmName, bool includeDelegators) {
            this.personID = personID;
            this.realmName = realmName;
            this.includeDelegators = includeDelegators;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="USE_ListPersonGroupsIncludingGlobal_INSTEADResponse", WrapperNamespace="http://iadb.org/", IsWrapped=true)]
    public partial class USE_ListPersonGroupsIncludingGlobal_INSTEAD1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=0)]
        public Reconfig.Domain.Handlers.Gum.GUMGroup[] USE_ListPersonGroupsIncludingGlobal_INSTEADResult;
        
        public USE_ListPersonGroupsIncludingGlobal_INSTEAD1() {
        }
        
        public USE_ListPersonGroupsIncludingGlobal_INSTEAD1(Reconfig.Domain.Handlers.Gum.GUMGroup[] USE_ListPersonGroupsIncludingGlobal_INSTEADResult) {
            this.USE_ListPersonGroupsIncludingGlobal_INSTEADResult = USE_ListPersonGroupsIncludingGlobal_INSTEADResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="USE_ListPersonGroups_INSTEAD", WrapperNamespace="http://iadb.org/", IsWrapped=true)]
    public partial class USE_ListPersonGroups_INSTEAD {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=0)]
        public int personID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=1)]
        public string realmName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=2)]
        public bool includeDelegators;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=3)]
        public bool includeGlobalGroups;
        
        public USE_ListPersonGroups_INSTEAD() {
        }
        
        public USE_ListPersonGroups_INSTEAD(int personID, string realmName, bool includeDelegators, bool includeGlobalGroups) {
            this.personID = personID;
            this.realmName = realmName;
            this.includeDelegators = includeDelegators;
            this.includeGlobalGroups = includeGlobalGroups;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="USE_ListPersonGroups_INSTEADResponse", WrapperNamespace="http://iadb.org/", IsWrapped=true)]
    public partial class USE_ListPersonGroups_INSTEAD1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=0)]
        public Reconfig.Domain.Handlers.Gum.GUMGroup[] USE_ListPersonGroups_INSTEADResult;
        
        public USE_ListPersonGroups_INSTEAD1() {
        }
        
        public USE_ListPersonGroups_INSTEAD1(Reconfig.Domain.Handlers.Gum.GUMGroup[] USE_ListPersonGroups_INSTEADResult) {
            this.USE_ListPersonGroups_INSTEADResult = USE_ListPersonGroups_INSTEADResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="USE_ListMembers_INSTEAD", WrapperNamespace="http://iadb.org/", IsWrapped=true)]
    public partial class USE_ListMembers_INSTEAD {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=0)]
        public string realmName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=1)]
        public bool allRealms;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=2)]
        public string gumGroupName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=3)]
        public bool includeDelegates;
        
        public USE_ListMembers_INSTEAD() {
        }
        
        public USE_ListMembers_INSTEAD(string realmName, bool allRealms, string gumGroupName, bool includeDelegates) {
            this.realmName = realmName;
            this.allRealms = allRealms;
            this.gumGroupName = gumGroupName;
            this.includeDelegates = includeDelegates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="USE_ListMembers_INSTEADResponse", WrapperNamespace="http://iadb.org/", IsWrapped=true)]
    public partial class USE_ListMembers_INSTEAD1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=0)]
        public Reconfig.Domain.Handlers.Gum.PersonDetails[] USE_ListMembers_INSTEADResult;
        
        public USE_ListMembers_INSTEAD1() {
        }
        
        public USE_ListMembers_INSTEAD1(Reconfig.Domain.Handlers.Gum.PersonDetails[] USE_ListMembers_INSTEADResult) {
            this.USE_ListMembers_INSTEADResult = USE_ListMembers_INSTEADResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="USE_IsUserInGroup_INSTEAD", WrapperNamespace="http://iadb.org/", IsWrapped=true)]
    public partial class USE_IsUserInGroup_INSTEAD {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=0)]
        public int personID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=1)]
        public string gumGroupName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=2)]
        public bool includeDelegators;
        
        public USE_IsUserInGroup_INSTEAD() {
        }
        
        public USE_IsUserInGroup_INSTEAD(int personID, string gumGroupName, bool includeDelegators) {
            this.personID = personID;
            this.gumGroupName = gumGroupName;
            this.includeDelegators = includeDelegators;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="USE_IsUserInGroup_INSTEADResponse", WrapperNamespace="http://iadb.org/", IsWrapped=true)]
    public partial class USE_IsUserInGroup_INSTEAD1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=0)]
        public bool USE_IsUserInGroup_INSTEADResult;
        
        public USE_IsUserInGroup_INSTEAD1() {
        }
        
        public USE_IsUserInGroup_INSTEAD1(bool USE_IsUserInGroup_INSTEADResult) {
            this.USE_IsUserInGroup_INSTEADResult = USE_IsUserInGroup_INSTEADResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="USE_IsUserInGroupRealm_INSTEAD", WrapperNamespace="http://iadb.org/", IsWrapped=true)]
    public partial class USE_IsUserInGroupRealm_INSTEAD {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=0)]
        public int personID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=1)]
        public string gumGroupName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=2)]
        public string realmName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=3)]
        public bool includeDelegators;
        
        public USE_IsUserInGroupRealm_INSTEAD() {
        }
        
        public USE_IsUserInGroupRealm_INSTEAD(int personID, string gumGroupName, string realmName, bool includeDelegators) {
            this.personID = personID;
            this.gumGroupName = gumGroupName;
            this.realmName = realmName;
            this.includeDelegators = includeDelegators;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="USE_IsUserInGroupRealm_INSTEADResponse", WrapperNamespace="http://iadb.org/", IsWrapped=true)]
    public partial class USE_IsUserInGroupRealm_INSTEAD1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iadb.org/", Order=0)]
        public bool USE_IsUserInGroupRealm_INSTEADResult;
        
        public USE_IsUserInGroupRealm_INSTEAD1() {
        }
        
        public USE_IsUserInGroupRealm_INSTEAD1(bool USE_IsUserInGroupRealm_INSTEADResult) {
            this.USE_IsUserInGroupRealm_INSTEADResult = USE_IsUserInGroupRealm_INSTEADResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GUMSoapChannel : Reconfig.Domain.Handlers.Gum.GUMSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GUMSoapClient : System.ServiceModel.ClientBase<Reconfig.Domain.Handlers.Gum.GUMSoap>, Reconfig.Domain.Handlers.Gum.GUMSoap {
        
        public GUMSoapClient() {
        }
        
        public GUMSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GUMSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GUMSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GUMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ListRealms(string langCode) {
            return base.Channel.ListRealms(langCode);
        }
        
        public System.Data.DataTable ListRealmsByGroup(string langCode, string gumGroupName) {
            return base.Channel.ListRealmsByGroup(langCode, gumGroupName);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonAuth ValidateAD(string domain, string userName) {
            return base.Channel.ValidateAD(domain, userName);
        }
        
        public System.Data.DataTable ListGroupsInRealms(string realmName, string groupTypeCode) {
            return base.Channel.ListGroupsInRealms(realmName, groupTypeCode);
        }
        
        public Reconfig.Domain.Handlers.Gum.GUMGroup[] ListGroupsInGroupRecursive(int groupID, string groupName, string realmName, int recursionDepth) {
            return base.Channel.ListGroupsInGroupRecursive(groupID, groupName, realmName, recursionDepth);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonDetails GetPersonInfo(int personID) {
            return base.Channel.GetPersonInfo(personID);
        }
        
        public Reconfig.Domain.Handlers.Gum.BankEmployeeDetails GetBankEmployeeInfo(string username) {
            return base.Channel.GetBankEmployeeInfo(username);
        }
        
        public Reconfig.Domain.Handlers.Gum.BankEmployeeDetails[] GetBankEmployeeList() {
            return base.Channel.GetBankEmployeeList();
        }
        
        public bool IsUserInGroup(int personID, string gumGroupName, bool includeDelegators) {
            return base.Channel.IsUserInGroup(personID, gumGroupName, includeDelegators);
        }
        
        public bool IsUserInGroupRealm(int personID, string gumGroupName, string realmName, bool includeDelegators) {
            return base.Channel.IsUserInGroupRealm(personID, gumGroupName, realmName, includeDelegators);
        }
        
        public Reconfig.Domain.Handlers.Gum.GUMGroup GetGroupInfo(string gumGroupName, string realmName, bool allRealms) {
            return base.Channel.GetGroupInfo(gumGroupName, realmName, allRealms);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonAuth ValidateExternal(string oneTimeToken) {
            return base.Channel.ValidateExternal(oneTimeToken);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonDetails[] ListDelegates(int personID, string realmName, bool allRealms) {
            return base.Channel.ListDelegates(personID, realmName, allRealms);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonDetails[] ListDelegators(int personID, string realmName) {
            return base.Channel.ListDelegators(personID, realmName);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonDetails[] ListPersonContacts(int personID, string gumGroupName, string realmName) {
            return base.Channel.ListPersonContacts(personID, gumGroupName, realmName);
        }
        
        public System.Data.DataTable ListApplications(string realmName, bool includeGlobal, string langCode) {
            return base.Channel.ListApplications(realmName, includeGlobal, langCode);
        }
        
        public System.Data.DataTable ListPersonRealms(int personID, bool includeDelegators) {
            return base.Channel.ListPersonRealms(personID, includeDelegators);
        }
        
        public Reconfig.Domain.Handlers.Gum.GUMGroup[] ListPersonGroupsIncludingGlobal(int personID, string realmName, bool includeDelegators, bool showGroupData) {
            return base.Channel.ListPersonGroupsIncludingGlobal(personID, realmName, includeDelegators, showGroupData);
        }
        
        public Reconfig.Domain.Handlers.Gum.GUMGroup[] ListPersonGroups(int personID, string realmName, bool includeDelegators, bool includeGlobalGroups, bool showGroupData) {
            return base.Channel.ListPersonGroups(personID, realmName, includeDelegators, includeGlobalGroups, showGroupData);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonDetails CreatePerson(
                    string lastName, 
                    string firstName, 
                    string alias, 
                    int applicationID, 
                    System.DateTime dateOfBirth, 
                    string genderCD, 
                    string streetAddress, 
                    int cityID, 
                    string postalCode, 
                    string email, 
                    string phoneNumber, 
                    int formOfAddressID, 
                    string preferredLanguage, 
                    string comments, 
                    string nationalityCD, 
                    int createdByPersonID) {
            return base.Channel.CreatePerson(lastName, firstName, alias, applicationID, dateOfBirth, genderCD, streetAddress, cityID, postalCode, email, phoneNumber, formOfAddressID, preferredLanguage, comments, nationalityCD, createdByPersonID);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonDetails UpdatePerson(int personID, System.DateTime dateOfBirth, string genderCD, string streetAddress, int cityID, string postalCode, string email, string phoneNumber, int formOfAddressID, string preferredLanguage, string comments, int updatedByPersonID) {
            return base.Channel.UpdatePerson(personID, dateOfBirth, genderCD, streetAddress, cityID, postalCode, email, phoneNumber, formOfAddressID, preferredLanguage, comments, updatedByPersonID);
        }
        
        public string CreatePersonAlias(int personID, string lastName, string firstName, string alias, int applicationID, bool setAsPreferredAlias, int createdByPersonID) {
            return base.Channel.CreatePersonAlias(personID, lastName, firstName, alias, applicationID, setAsPreferredAlias, createdByPersonID);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonGroupMembership CreatePersonGroupMembership(int personID, int gumGroupID, System.DateTime positionFromDate, System.DateTime positionToDate, string positionEmail, string positionPhone, string positionCountryCD, int positionRanking1, int positionRanking2, int positionTitleID, string positionTitleText, string positionOffice, bool positionPointOfContact, int createdByPersonID) {
            return base.Channel.CreatePersonGroupMembership(personID, gumGroupID, positionFromDate, positionToDate, positionEmail, positionPhone, positionCountryCD, positionRanking1, positionRanking2, positionTitleID, positionTitleText, positionOffice, positionPointOfContact, createdByPersonID);
        }
        
        public int UpdatePersonGroupMembership(
                    int personGroupMembershipID, 
                    System.DateTime positionFromDate, 
                    System.DateTime positionToDate, 
                    string positionEmail, 
                    string positionPhone, 
                    string positionCountryCD, 
                    int positionRanking1, 
                    int positionRanking2, 
                    string positionOffice, 
                    string positionVIP, 
                    string positionTempVIP, 
                    bool positionPointOfContact, 
                    string positionInstContactType, 
                    string positionSkype, 
                    string positionTwitter, 
                    string positionComments, 
                    int titleID, 
                    string titleGender, 
                    string titleType, 
                    string titleShortEN, 
                    string titleShortES, 
                    string titleShortPT, 
                    string titleShortFR, 
                    string titleLongEN, 
                    string titleLongES, 
                    string titleLongPT, 
                    string titleLongFR, 
                    int updatedByPersonID) {
            return base.Channel.UpdatePersonGroupMembership(personGroupMembershipID, positionFromDate, positionToDate, positionEmail, positionPhone, positionCountryCD, positionRanking1, positionRanking2, positionOffice, positionVIP, positionTempVIP, positionPointOfContact, positionInstContactType, positionSkype, positionTwitter, positionComments, titleID, titleGender, titleType, titleShortEN, titleShortES, titleShortPT, titleShortFR, titleLongEN, titleLongES, titleLongPT, titleLongFR, updatedByPersonID);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonGroupMembership GetPersonGroupMembershipInfoByID(int personGroupMembershipID) {
            return base.Channel.GetPersonGroupMembershipInfoByID(personGroupMembershipID);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonGroupMembership GetPersonGroupMembershipInfo(int personID, int gumGroupId, System.DateTime fromDate) {
            return base.Channel.GetPersonGroupMembershipInfo(personID, gumGroupId, fromDate);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonGroupMembership UpdatePersonGroupMembershipExpirationDate(int personGroupMembershipID, System.DateTime expirationDate) {
            return base.Channel.UpdatePersonGroupMembershipExpirationDate(personGroupMembershipID, expirationDate);
        }
        
        public string AddPersonImageFromFile(int personID, string filePath) {
            return base.Channel.AddPersonImageFromFile(personID, filePath);
        }
        
        public string AddPersonImage(int personID, string pictureStream) {
            return base.Channel.AddPersonImage(personID, pictureStream);
        }
        
        public string GetPersonImageFullSize(string fileName) {
            return base.Channel.GetPersonImageFullSize(fileName);
        }
        
        public string GetPersonImage(string fileName) {
            return base.Channel.GetPersonImage(fileName);
        }
        
        public string GenerateOneTimePasscode(int personID, System.DateTime OTPExpirationDate) {
            return base.Channel.GenerateOneTimePasscode(personID, OTPExpirationDate);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonDetails[] ListMembers(string realmName, bool allRealms, string gumGroupName, bool includeDelegates, bool showGroupData) {
            return base.Channel.ListMembers(realmName, allRealms, gumGroupName, includeDelegates, showGroupData);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonDetails[] ListMemberships(string realmName, bool allRealms, string gumGroupName, bool includeDelegates, bool showGroupData) {
            return base.Channel.ListMemberships(realmName, allRealms, gumGroupName, includeDelegates, showGroupData);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonDetails[] ListEmailsByGroupNoRecursive(string realmName, string gumGroupName) {
            return base.Channel.ListEmailsByGroupNoRecursive(realmName, gumGroupName);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonGroupMembership UpdatePersonGroupMembershipRanking(int personGroupMembershipID, int ranking1, int ranking2) {
            return base.Channel.UpdatePersonGroupMembershipRanking(personGroupMembershipID, ranking1, ranking2);
        }
        
        public Reconfig.Domain.Handlers.Gum.CityDetails GetCityInfo(string cityID, string langCode) {
            return base.Channel.GetCityInfo(cityID, langCode);
        }
        
        public string _GetGroupRecursion(int gumGroupId) {
            return base.Channel._GetGroupRecursion(gumGroupId);
        }
        
        public string _GetGroupRecursionUp(int gumGroupId) {
            return base.Channel._GetGroupRecursionUp(gumGroupId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Reconfig.Domain.Handlers.Gum.USE_ListPersonGroupsIncludingGlobal_INSTEAD1 Reconfig.Domain.Handlers.Gum.GUMSoap.ADListPersonGroupsIncludingGlobal(Reconfig.Domain.Handlers.Gum.USE_ListPersonGroupsIncludingGlobal_INSTEAD request) {
            return base.Channel.ADListPersonGroupsIncludingGlobal(request);
        }
        
        public Reconfig.Domain.Handlers.Gum.GUMGroup[] ADListPersonGroupsIncludingGlobal(int personID, string realmName, bool includeDelegators) {
            Reconfig.Domain.Handlers.Gum.USE_ListPersonGroupsIncludingGlobal_INSTEAD inValue = new Reconfig.Domain.Handlers.Gum.USE_ListPersonGroupsIncludingGlobal_INSTEAD();
            inValue.personID = personID;
            inValue.realmName = realmName;
            inValue.includeDelegators = includeDelegators;
            Reconfig.Domain.Handlers.Gum.USE_ListPersonGroupsIncludingGlobal_INSTEAD1 retVal = ((Reconfig.Domain.Handlers.Gum.GUMSoap)(this)).ADListPersonGroupsIncludingGlobal(inValue);
            return retVal.USE_ListPersonGroupsIncludingGlobal_INSTEADResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Reconfig.Domain.Handlers.Gum.USE_ListPersonGroups_INSTEAD1 Reconfig.Domain.Handlers.Gum.GUMSoap.ADListPersonGroups(Reconfig.Domain.Handlers.Gum.USE_ListPersonGroups_INSTEAD request) {
            return base.Channel.ADListPersonGroups(request);
        }
        
        public Reconfig.Domain.Handlers.Gum.GUMGroup[] ADListPersonGroups(int personID, string realmName, bool includeDelegators, bool includeGlobalGroups) {
            Reconfig.Domain.Handlers.Gum.USE_ListPersonGroups_INSTEAD inValue = new Reconfig.Domain.Handlers.Gum.USE_ListPersonGroups_INSTEAD();
            inValue.personID = personID;
            inValue.realmName = realmName;
            inValue.includeDelegators = includeDelegators;
            inValue.includeGlobalGroups = includeGlobalGroups;
            Reconfig.Domain.Handlers.Gum.USE_ListPersonGroups_INSTEAD1 retVal = ((Reconfig.Domain.Handlers.Gum.GUMSoap)(this)).ADListPersonGroups(inValue);
            return retVal.USE_ListPersonGroups_INSTEADResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Reconfig.Domain.Handlers.Gum.USE_ListMembers_INSTEAD1 Reconfig.Domain.Handlers.Gum.GUMSoap.ADListMembers(Reconfig.Domain.Handlers.Gum.USE_ListMembers_INSTEAD request) {
            return base.Channel.ADListMembers(request);
        }
        
        public Reconfig.Domain.Handlers.Gum.PersonDetails[] ADListMembers(string realmName, bool allRealms, string gumGroupName, bool includeDelegates) {
            Reconfig.Domain.Handlers.Gum.USE_ListMembers_INSTEAD inValue = new Reconfig.Domain.Handlers.Gum.USE_ListMembers_INSTEAD();
            inValue.realmName = realmName;
            inValue.allRealms = allRealms;
            inValue.gumGroupName = gumGroupName;
            inValue.includeDelegates = includeDelegates;
            Reconfig.Domain.Handlers.Gum.USE_ListMembers_INSTEAD1 retVal = ((Reconfig.Domain.Handlers.Gum.GUMSoap)(this)).ADListMembers(inValue);
            return retVal.USE_ListMembers_INSTEADResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Reconfig.Domain.Handlers.Gum.USE_IsUserInGroup_INSTEAD1 Reconfig.Domain.Handlers.Gum.GUMSoap.ADIsUserInGroup(Reconfig.Domain.Handlers.Gum.USE_IsUserInGroup_INSTEAD request) {
            return base.Channel.ADIsUserInGroup(request);
        }
        
        public bool ADIsUserInGroup(int personID, string gumGroupName, bool includeDelegators) {
            Reconfig.Domain.Handlers.Gum.USE_IsUserInGroup_INSTEAD inValue = new Reconfig.Domain.Handlers.Gum.USE_IsUserInGroup_INSTEAD();
            inValue.personID = personID;
            inValue.gumGroupName = gumGroupName;
            inValue.includeDelegators = includeDelegators;
            Reconfig.Domain.Handlers.Gum.USE_IsUserInGroup_INSTEAD1 retVal = ((Reconfig.Domain.Handlers.Gum.GUMSoap)(this)).ADIsUserInGroup(inValue);
            return retVal.USE_IsUserInGroup_INSTEADResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Reconfig.Domain.Handlers.Gum.USE_IsUserInGroupRealm_INSTEAD1 Reconfig.Domain.Handlers.Gum.GUMSoap.ADIsUserInGroupRealm(Reconfig.Domain.Handlers.Gum.USE_IsUserInGroupRealm_INSTEAD request) {
            return base.Channel.ADIsUserInGroupRealm(request);
        }
        
        public bool ADIsUserInGroupRealm(int personID, string gumGroupName, string realmName, bool includeDelegators) {
            Reconfig.Domain.Handlers.Gum.USE_IsUserInGroupRealm_INSTEAD inValue = new Reconfig.Domain.Handlers.Gum.USE_IsUserInGroupRealm_INSTEAD();
            inValue.personID = personID;
            inValue.gumGroupName = gumGroupName;
            inValue.realmName = realmName;
            inValue.includeDelegators = includeDelegators;
            Reconfig.Domain.Handlers.Gum.USE_IsUserInGroupRealm_INSTEAD1 retVal = ((Reconfig.Domain.Handlers.Gum.GUMSoap)(this)).ADIsUserInGroupRealm(inValue);
            return retVal.USE_IsUserInGroupRealm_INSTEADResult;
        }
    }
}
